################################################################################
# Mergeable configuration
################################################################################
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'PR title check'
    validate:
      - do:
        validate:
          - do: changeset
            must_include:
              regex: 'ipnext/arch/*'




