

.pr-checklist-path: &pr-checklist-path
 when: pull_request.*
 name: ' Test case path check'
 validate:
    - do: changeset
      must_include:
        regex:'ipnext/arch/*'


version: 2
mergeable:
    - *pr-checklist-path
    