################################################################################
# Mergeable configuration
################################################################################
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'PR test path check'
    validate:
      - do: changeset
        must_include:
        regex: 'ipnext/aas/*'




