################################################################################
# Mergeable configuration
################################################################################
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'PR path check'
    validate:
      - do: and
        validate:
          - do: changeset
            must_include:
              regex: 'ipnext/ass/*'
          - do: changeset
            must_include:
              regex: 'ipnext/arch/*'
              

