version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: changeset
        must_include:
          regex: 'ipnext/aas/*'
          message: 'new test case added'
      - do: payload
        draft:
          boolean:
            match: true
            message: 'changes in test case path'
    pass:
      - do: comment
        draft:
          boolean:
            match: true
            message: changes idenfied in test case path
