version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: changeset
        must_include:
          regex: 'ipnext/aas/*'
          message: 'new test case added'
    pass:
      - do: merge
        merge_method: 'squash'
      - do: checks
        status: 'success'