version: 2
mergeable:
   - when: pull_request.*, pull_request_review.*
     name: 'PR title check'
     validate:
      - do: or
        validate:
          - do: changeset
            must_exclude:
              regex: 'ipnext/aas/*'
          - do: and
            validate:
              - do: changeset
                must_include:
                  regex: 'ipnext/arch/*'
              - do: title
                begins_with:
                  match: [ 'test_' ]